name: Build and Release BuraqManager

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags like v0.1.0

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Build executable
        run: poetry run pyinstaller --name BuraqManager --noconsole main.py

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/BuraqManager.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}