name: CI/CD for Desktop App

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest

      - name: Build executable
        run: poetry run pyinstaller --name MyDesktopApp --onefile --add-data "data.db;." main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyDesktopApp-${{ matrix.os }}
          path: |
            dist/MyDesktopApp*
            data.db

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/MyDesktopApp-ubuntu-latest/MyDesktopApp
            artifacts/MyDesktopApp-ubuntu-latest/data.db
            artifacts/MyDesktopApp-windows-latest/MyDesktopApp.exe
            artifacts/MyDesktopApp-windows-latest/data.db
            artifacts/MyDesktopApp-macos-latest/MyDesktopApp
            artifacts/MyDesktopApp-macos-latest/data.db
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}