name: Build and Release

on:
  release:
    types: [published]

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Build executable
        run: |
          poetry run pyinstaller --name BuraqManager --noconsole --add-data "buraqmanager.db;." main.py

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/BuraqManager.exe
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}