name: CI/CD for BuraqManager

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root
        env:
          POETRY_VENV_IN_PROJECT: true

      - name: Run tests
        run: poetry run pytest
        if: matrix.os == 'ubuntu-latest'  # Run tests only once

      - name: Build executable
        run: |
          poetry run pyinstaller --name BuraqManager --onefile --add-data "buraqmanager.db${{ matrix.os == 'windows-latest' && ';' || ':' }}." main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BuraqManager-${{ matrix.os }}
          path: dist/BuraqManager*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/BuraqManager-ubuntu-latest/BuraqManager
            artifacts/BuraqManager-windows-latest/BuraqManager.exe
            artifacts/BuraqManager-macos-latest/BuraqManager
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}